### ISSUE TITLE
[epic] refactor history API (logging of cases)

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#154]
## User story 
As a case worker I want to have an overview of the case I am working on, e.g. what tasks are already done, what data objects are there. As a process analyst I want to access the event log of a case model (previously called "history") to perform analysis based on this data.

## Explanation
The expected functionality is already there, but needs to be refactored. Currently, there are *three separate API endpoints for getting the history of activities, data object states, and data object attributes.* These endpoints **should be merged**, to decrease the number of requests the frontend has to send.

Furthermore, there is an endpoint `export`, which creates a XML document in the [XES format](http://www.xes-standard.org/) containing all traces of a case model. We should discuss (with @flxw) what information should be included in such an event log.

Some events of interest are so far not logged in the history: the occurrence of BPMN events and the instantiation of new fragment instances. **They should be included** in the history.

The different kind of "events" that are part of the case history need a common form, currently they are represented by instances of the class `LogEntry`. This would probably need to be extended to cover BPMN events and fragment instantiation. 

Another important consideration is whether the history should be **represented as a total or partial order**. Conceptually it is a partial order, because activities in different fragment instances can be executed concurrently without interfering. Also @PeterSchwarzHPI is currently implementing a unfolding feature for case models, which uses partial orders.

## Feature breakdown
- [ ] merge endpoints for activities, DO states, DO attributes into `.../case/123/history`
- [ ] query filter in API to get history in different granularity levels (e.g. all activity lifecycle transitions vs. just begin and terminate)
- [ ] include BPMN events and fragment instances in the history
