### ISSUE TITLE
[epic] improve documentation

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#157]
As a developer and contributor to the Chimera project I need up-to-date and in-depth information about the Chimera case engine and guidelines on how to develop it further. In #144 the structure of the wiki was revised according to a new information architecture. **Now, we need to complete the content of the wiki.**

Let's use this issue to collect the parts of the wiki that need to be extended.

## Related Issues
- [ ] #153 document test database usage and testing guide
- [ ] #151 document API v3
- [ ] describe **pull requests** in CONTRIBUTING.md
- [ ] write guide on [IDE configuration](https://github.com/bptlab/chimera/wiki/IDE-Configuration)
