### ISSUE TITLE
Epic: Roles for Activities

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#77]
As a case modeler I want to express, that certain activities can only be executed by case workers who have a certain organizational role. This is necessary for the BPT bookshelf usecase, where only certain persons can decide whether to order a requested book.

Building on top of the basic user management capabilities specified in #9 case modelers need to define organizational roles and assign them to members of an organization. Gryphon needs to be extended with an additional attribute for activities, that contains the organizational role which is required to execute the activity (this attribute is optional, if it is left empty the role 'member' is assumed).

Chimera needs to parse the 'role' attribute. During execution, if such an activity is enabled and the frontend asks for enabled activity, the backend needs to check, whether the user has the required role. Only then is the activity included in the list of enabled activities send to the frontend. This check has also to occur when users want to begin an activity.

- [ ] ~Model roles.~ **Unclear where this is done, whether in Gryphon or Chimera, see #80**
- [x] bptlab/gryphon#27 Add new attribute 'role' for activities in bpmn.io, serialize and export the new 'role' attribute
- [x] #79 parse the 'role' attribute and store it in the activity
- [x] #78 when executing cases check whether user has required role to execute activity

**Comment by marhew** [comment]
We should consider to make required roles of an activity **configurable in the future**, similar to EmailTasks. In this way, it would be possible to adapt the required roles without having to re-model the fragment. However, this also has potential problems for cases that are already running: will they use the updated configuration?

**Comment by marhew** [comment]
The frontend to model roles is moved to release 1.6, in which the UI will be redesigned.
