### ISSUE TITLE
API refactoring

### ISSUE THREAD

**Issue by marhew** [bptlab/chimera#99]
In the light of the UI redesign (see #4) and the added endpoints for user management (see #9), we should also re-evaluate and eventually refactor the REST API design. For example, the swagger documentation is inconsistent with the implemented API (see #98). Also, naming is outdated, "scenario" should be changed to "case model".

## Discussion Results
- we keep the versioning, the refactored API will use `api/v3/` as base
- we will use the plural convention for resource names, i.e. `casemodels/123/cases`
- we will no longer use different base paths for events, history, and the main interface, instead the complete API will be reachable at `api/v3/`

## Open Question: UUIDs or auto-incremented numbers? 
- auto-incremented numbers are more (human) readable and make it easier to debug the API 
- with numbers, users can infer and access Ids of other resources
- should numbers be unique among case models, cases, activities etc. or only for one layer? E.g. is `casemodels/3/cases/3/dataobjects/3/attributes/3` a valid URL?
- if we keep UUID as key in the database, we need to make a mapping in the REST layer
- **does EclipseLink generate the UUIDs and uses them, or does it have separate identifiers?**

Features
- [ ] discuss usage of UUIDs vs. incremental numbering (**in this issue**)
- [x] update naming of scenario and instance
- [x] #102 create a document outlining our API design principles 
- [x] #100 swagger documentation should be automatically generated
- [x] #96 swagger documentation consistency
- [x] #75 API for user management
- [x] #98 discuss & decide separated base paths

**Comment by friedow** [comment]
http://jsonapi.org/ as a standard should be very helpful for the refactoring.

**Comment by marhew** [comment]
@janwestphal306 The jsonapi spec is very verbose and the responses are highly nested. Although I like how links are included and preloaded in the `included` key. **I would rather have responses that directly reflect the object structure of the resources, so we can use Bean classes.** We can include a query parameter `?complete` that would indicate to load the complete resource, e.g. an organization with all its members, owners, roles, or a complete case.

**Comment by friedow** [comment]
I disagree with changing the response object. The main benefit of the jsonapi standard is that it is a standard and therefore many libraries are built on it. Take https://www.npmjs.com/package/json-api-wrapper as an example, it is a generic API wrapper build exactly on the standard. Therefore I'd strongly advise implementing the standard, exactly as it is proposed.

**Comment by janwestphal306** [comment]
@marhew The refactored chimera would allow to split the long Url `v3/organizations/{organizationId}/casemodels/{casemodelId}/cases/{caseId}` in `v3/organizations/{organizationId}`, `v3/casemodels/{casemodelId}` and ``v3/cases/{caseId}` and would still achieve the same behavior if the we validate in the request filter. Would this be desired?

**Comment by marhew** [comment]
I think it is better to keep the hierarchy of resources visible.

**Comment by marhew** [comment]
For the 1.5 release we will stick to UUIDs. However, for 2.0 we should change IDs to a shorter and more readable format.
